figure()
plot(1:10,1:10)
xlabel('X AXIS')
ylabel('Y AXIS')
title('GRAPH OF THINGS')
legend('GRAPH')
figure()
plot(-10:-1,1:10)
xlabel('X AXIS')
ylabel('Y AXIS')
title('GRAPH OF THINGS')
legend('GRAPH')